use etl;
select * from healthcare;
#1. Retrieve the names of all patients in the database.  
select name from healthcare;
#2. List the unique medical conditions present in the dataset.  
select distinct Medical_condition from healthcare;
#3. Find the total number of doctors in the healthcare system.
 select count(doctor) from healthcare;
#4. Retrieve the details of all female patients.  
select*from healthcare where gender='Female';
#5. what is the average age of patients in the database. 
select avg(age) from healthcare;
#6. Identify the patients who have more than one medical condition. 
select count(Medical_Condition),name from healthcare group by name having count(Medical_Condition)>1;
#7. List the names of all doctors.  
select Doctor from healthcare;
#8.Identify the most common medical condition among patients. 
select count(*),Medical_Condition from healthcare group by Medical_Condition order by count(*) desc limit 1;
#9.Find the patients who are older than 60 years and have diabetes. 
select name from healthcare where age>60 and Medical_Condition='diabetes';
#10.Calculate the total revenue generated by the healthcare system.  
select sum(Billing_Amount) from healthcare;
#11.Find the doctor with the oldest patient
select Name,Doctor,Age from healthcare where Age=(select max(age) from healthcare)limit 1;
#12.Calculate the average duration of medical visits. 
select avg(duration) from healthcare;
#13.Give the names of patients whose name starts with A.
select * from healthcare where name like 'A%';
#14.How many male and female patients are there in dataset.  
select gender,count(*) from healthcare group by gender;
#15.how many patients are normal.  
select count(*) from healthcare where Test_Results='Normal';
#16.how many patients are abnormal or Inconclusive.
select count(*) from healthcare where Test_Results!='Normal';
#17.how many patients of blood group AB+ are there of age above 52. 
select*from healthcare where Blood_Type='AB+' and age>52;
#18. how many patients have paid the bill above 24890. 
select count(*) from healthcare where Billing_Amount>24890;
#19. what are the names of patients having Asthma. 
select name, Medical_Condition from healthcare where Medical_Condition='Asthma';
#20. how many patients have cancer. 
select count(*) from healthcare where Medical_Condition='cancer';
#21. what are the names and blood groups of patients admitted to room no. 292. 
select name,Blood_Type,Room_Number from healthcare where Room_Number=292;
#22. how many males have Arthritis.
select count(*) from healthcare where Gender='Male' and Medical_Condition='Arthritis';
#23. How many patients were admitted to Harris and Sons hospital. 
select count(*) from healthcare where Hospital='Harris and Sons';
#24. what are the names of patients whose Insurance Provider are Cigna. 
select name, Insurance_Provider from healthcare where Insurance_Provider='Cigna';
#25. Name the Medical Condition having patients whose ages is greater than average age
select count(*),Medical_Condition from healthcare where Age>(select avg(Age) from healthcare) group by Medical_Condition;
